### ISSUE TITLE
Define the difference between speaking event that has training and a pure training event and a pure speaking event.

### ISSUE THREAD

**Issue by PiaScott** [18F/training#11]
If an employee speaks at conference does that count toward their training for the FY?

**Comment by StephanieRivera** [comment]
I'm thinking the difference might be between what is a conference (where one could speak or attend) and what is training.  

I've found both GSA definitions here under Definitions 
https://docs.google.com/a/gsa.gov/document/d/18VcWDZbXw7lNAHj_OJbRMZBacEgO2IKJZSsTqy33gOY/edit

**Comment by jackiekazil** [comment]
We are generally recognizing a speaking event as a speaking event, not training.
