### ISSUE TITLE
Proposal training by quantity or by budget by group or person

### ISSUE THREAD

**Issue by PiaScott** [18F/training#13]
Is the number of training sessions an employee is eligible to attend determined by the number of session or the budget expense?  For example, if an employee identifies a half-day skill-set training workshop for $75, does that count toward their training for the FY?

**Comment by jackiekazil** [comment]
What is the end goal of this task? Is this research? Is this proposing a policy section?

**Comment by jackiekazil** [comment]
Success would be doing user interviews and drafting a couple of bullets how to determine how $ is divided.

**Comment by StephanieRivera** [comment]
Greg would like the budgeted amount broken out at the person level.

**Comment by jackiekazil** [comment]
When I read your comment,  I read it as the following -- if we have a hypothetical $1000 and we have 100 employees, then each employee has a training budget of $10.

Two questions --  
1. How do we account for folks who haven't joined yet, but will join? 
2. How would we handle a situation where one person needs more training? (Example: $11 or $15)

**Comment by cscairns** [comment]
let's lay out the different options and some hypothetical examples using numbers to communicate the tradeoffs (sort of like jackie did above)

**Comment by jackiekazil** [comment]
Budget tickets: #5, #15

**Comment by russu** [comment]
In previous lives, we set a budget per person, with some potential variables.

Example:
Each person has a budget of $X per year

I like breaking down this down, potentially into 2 buckets: Event cost & Travel & Lodging.

I think that if someone wants to go to an expensive event that caps out their budget, and someone else wants to select a couple of smaller events, that should be okay; value isn't something that is entirely non-subjective, and it allows people some freedom and flexibility to pick and choose, or find specialty items.

Variables: Sometimes, a workshop might make sense to bring in-house versus sending a person (or persons) to. Is there an internal "all-team" budget for such trainings that falls outside of the per-person budget, as well? Should there be (I suspect: yes) Do we also take from individual budgets for this? (not sure; could be an option)

Discretion: If person X wants to attend an event that is slightly over budget, and can make trade-offs in T&L, there should be a bit of an ability to be flexible. Should person x also be able to pay the difference themselves if an event is over their budget? (I suspect yes, not sure as to the complexity and it is likely more dependent upon the event producers)

# 

Budget amounts could be flat, could be by rating, etc. Lots of options here to determine an approach. We could mine lanyrd.com for a handful of events, etc.

**Comment by StephanieRivera** [comment]
More information 

Team Ops is estimating 179 FTE for FY15.  This takes in account the hiring done by the Hiring Team.  

Budget and Funding information
Training Cap FY15 = $322,917  (approx 1.5% of PC&B (salary plus benefits for est 179 FTE FY15) 
Employee estimate  $1,804/person
To date 18F has used $0
Limits are set by FPA (Financial Planning Application.  Changes would require a SAPi adjustment

Travel Cap FY15 = $215,000  (approx 0.8% PC&B) 
Employee estimate $1,200/person
To date  have $179K left (w/o offsite calculated)
Limit set by 18F office

**Comment by StephanieRivera** [comment]
Also more information.  

Training requires one approval from one budget line

Travel require a separate approval from another budget line.  

You can not take fundings from one to pay for another. 

Thus, an employee is inherently incentivized to train locally.  It should also be noted that I do not think that was the intent of breaking them out.

**Comment by jackiekazil** [comment]
"an employee is inherently incentivized to train locally." good to note -- that makes sense. I didn't know that.

**Comment by jackiekazil** [comment]
After some user interviews and exploration, we are looking at dividing the budget by person per financial year. For new employees, they are accounted for in projections. 

Next step -- review w/ @aaronsnow.

**Comment by jackiekazil** [comment]
@StephanieRivera, please update and close.

**Comment by jackiekazil** [comment]
This is in the drafted policy -- https://docs.google.com/a/gsa.gov/document/d/18VcWDZbXw7lNAHj_OJbRMZBacEgO2IKJZSsTqy33gOY/edit#
