### ISSUE TITLE
What is the FY15 Training Budget?

### ISSUE THREAD

**Issue by StephanieRivera** [18F/training#15]
Due 2/13

**Comment by StephanieRivera** [comment]
Training Cap FY15 = $322,917  (approx 1.5% of PC&B (salary plus benefits for est 179 FTE) 
Employee estimate  $1,804/person
To date 18F has used $0
Limits are set by FPA (Financial Planning Application.  Changes would require a SAPi adjustment

Travel Cap FY15 = $215,000  (approx 0.8% PC&B) 
Employee estimate $1,200/person
To date  have $179K left (w/o offsite calculated)
Limit set by 18F office

**Comment by StephanieRivera** [comment]
I brought this up with Greg. I suggested grouping the training at the functional supervisor level.  Allowing the supervisor to have a grouping a funds (travel and training) for their staff.  He very clearly said, he wanted it parsed out at the person level.  Not at the group or supervisor level.

**Comment by PiaScott** [comment]
That ensures equitable treatment of all employees.  There are some other
factors, we need to discuss in Friday's stand up.

On Tue, Feb 17, 2015 at 7:33 PM, Stephanie Rivera notifications@github.com
wrote:

> I brought this up with Greg. I suggested grouping the training at the
> functional supervisor level. Allowing the supervisor to have a grouping a
> funds (travel and training) for their staff. He very clearly said, he
> wanted it parsed out at the person level. Not at the group or supervisor
> level.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/training/issues/15#issuecomment-74786946.

## 

_Pia Scott_
U.S. General Services Administration
1800 F Street, NW
Washington, DC 20405
pia.scott@gsa.gov

"A Century of Black Life, History, and Culture", 2015 Black History Month
Theme
