### ISSUE TITLE
How does someone get reimbursed for the conference and travel after they are approved? 

### ISSUE THREAD

**Issue by jackiekazil** [18F/training#16]

**Comment by PiaScott** [comment]
It depends.  If the employee has a Travel Authorization, then the employee would complete the voucher in Concur and would receive reimbursement. If the employee has been approved, but does not have a Travel Authorization, then . . .research required.

**Comment by PiaScott** [comment]
If IDP approved, Salesforce approval secured, Travel Authorization approved, reimbursement secure via Concur voucher process.
