### ISSUE TITLE
Create a draft of what the approval process workflow might look like 

### ISSUE THREAD

**Issue by jackiekazil** [18F/training#17]
This needs to be done, because there is confusion around the actual process.
This can be a simple bullet list or a very simple sketch -- this is not a final doc. 
After this is created, we can discuss if we need a remake on the quicklook guide or if it still stands.

If we need to discuss in the a meeting -- we can do that, but I thought it would better to have the meeting after we have another possible draft.

**Comment by StephanieRivera** [comment]
Step by step draft process can be found here under "Employee Approval Process for Training"

https://docs.google.com/a/gsa.gov/document/d/18VcWDZbXw7lNAHj_OJbRMZBacEgO2IKJZSsTqy33gOY/edit
