### ISSUE TITLE
Rename the 18F Speaker Request  spreadsheet be renamed to reflect training? 

### ISSUE THREAD

**Issue by StephanieRivera** [18F/training#19]
Thinking it may be nice to have training in the title.  So that people know where to go.

**Comment by StephanieRivera** [comment]
Give examples of "Red Flags" for staff to be mindful of when requesting training.  Red flags language used in the quick look guide.

**Comment by StephanieRivera** [comment]
Does the Salesforce Form included a section for travel cost calculation?

**Comment by PiaScott** [comment]
See Column Q

On Tue, Feb 17, 2015 at 2:42 PM, Stephanie Rivera <notifications@github.com>
wrote:

> Assigned #19 <https://github.com/18F/training/issues/19> to @PiaScott
> <https://github.com/PiaScott>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/training/issues/19#event-237181690>.
>



-- 
*Pia Scott*
U.S. General Services Administration
1800 F Street, NW
Washington, DC 20405
pia.scott@gsa.gov

"A Century of Black Life, History, and Culture", 2015 Black History Month
Theme

**Comment by PiaScott** [comment]
Yes.

On Tue, Feb 17, 2015 at 3:10 PM, Stephanie Rivera notifications@github.com
wrote:

> Does the Salesforce Form included a section for travel cost calculation?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/training/issues/19#issuecomment-74742905.

## 

_Pia Scott_
U.S. General Services Administration
1800 F Street, NW
Washington, DC 20405
pia.scott@gsa.gov

"A Century of Black Life, History, and Culture", 2015 Black History Month
Theme

**Comment by PiaScott** [comment]
The spreadsheet has a training tab, please see Quick Look guide.
