### ISSUE TITLE
How does an employee voucher for training expenses?  

### ISSUE THREAD

**Issue by StephanieRivera** [18F/training#23]
Can this be done through Concure ?

**Comment by PiaScott** [comment]
Yes.

On Tue, Feb 17, 2015 at 6:39 PM, Stephanie Rivera notifications@github.com
wrote:

> Can this be done through Concure ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/training/issues/23.

## 

_Pia Scott_
U.S. General Services Administration
1800 F Street, NW
Washington, DC 20405
pia.scott@gsa.gov

"A Century of Black Life, History, and Culture", 2015 Black History Month
Theme

**Comment by StephanieRivera** [comment]
even if there is no travel?

**Comment by PiaScott** [comment]
SF-182
Payment of training by employer prior to attendance is the normal course.

**Comment by jackiekazil** [comment]
Notes: 
- Travel is through Concur. Training payment is separate. (Food is per diem, which is auto calculated. Tips not included.)
- You cannot vouch for training, but you can vouch for expenses related to the travel -- like taxi, etc.
- Training has to be paid before the training government charge card if under the threshold or SF-182. (The threshold is $3000.) (In the event of SF-182, then the vender gets electronic payment.)
- If you have a bulk purchase --- you should reach out to Ric. (This would probably end up as a simplified acquisition.)
