### ISSUE TITLE
Team read over the GSA Workforce Learning and Development Policy

### ISSUE THREAD

**Issue by StephanieRivera** [18F/training#24]
Worth a skim if not a read.  

http://gsa.gov/portal/mediaId/194047/fileName/HRM_P_94101A_GSA_Workforce_Learning_and_Development_Policy_(Final_Signed_on_6-26-2014).action

**Comment by jackiekazil** [comment]
:+1:  I did a quick skim, but I am moving this to next sprint to spend a little more time with it.
