### ISSUE TITLE
Q: Can you voucher local travel expenses like parking or taxi?

### ISSUE THREAD

**Issue by jackiekazil** [18F/training#27]

**Comment by PiaScott** [comment]
Yes, local  travel can be reimbursed.  GSA recently updated its policy on local travel, OAS 5770.1.
Local travel includes transportation within a 50-mile radius of duty station or residence. Vouchers must be submitted via Concur. Approved local travel expenses include: Mass Transit, POV mileage, taxis and parking.  

Employees are encouraged to use public transportation when possible.  Mileage and parking for local travel are reimbursed, only the amount that exceeds the employee's normal daily transportation costs.  

Employee should not use the federal transit subsidy to conduct government business. The official use of transit subsidy covers only the employee's transportation to and from the employee's residence to the employee's duty station. Offices are encouraged to have public transportation tickets/tokens for employees, to reduced the administrative burden.
