### ISSUE TITLE
Research if metro card can used for local conference travel

### ISSUE THREAD

**Issue by jackiekazil** [18F/training#29]
From our policy docs.... 
"Employee should not use the federal transit subsidy to conduct government business. The official use of transit subsidy covers only the employee's transportation to and from the employee's residence to the employee's duty station. Offices are encouraged to have public transportation tickets/tokens for employees, to reduced the administrative burden."

Doc: https://docs.google.com/a/gsa.gov/document/d/18VcWDZbXw7lNAHj_OJbRMZBacEgO2IKJZSsTqy33gOY/edit#

**Comment by PiaScott** [comment]
"The subsidy is only intended to cover the costs of commuting to an employee’s official worksite/duty station and return to home. It is not intended to pay for local travel to/from/between other places of official business, such as travel to an offsite meeting location." OAS 5770.1
