### ISSUE TITLE
Similar repo: avoiding redundancy

### ISSUE THREAD

**Issue by jenniferthibault** [18F/training#33]
@jackiekazil, Mike let me know to check in with you, because it looks like this is similar(-ish) to what we've been working on over here: https://github.com/18F/hub-pages-private/blob/master/qa/virtual-training.md which is now part of "How to" on the hub. Interested in combining them?

**Comment by jackiekazil** [comment]
This repo has been about training policy creating. There doesn't seem to be overlap IMHO.

**Comment by jenniferthibault** [comment]
Great! Just wanted to make sure. If you learn of trainings offered while in training policy creating mode, please add to the list!
