### ISSUE TITLE
Is there a number limit to training sessions 18F employees are eligible to attend per FY?

### ISSUE THREAD

**Issue by PiaScott** [18F/training#4]
Is this limited to one per FY?

**Comment by jackiekazil** [comment]
We are limiting to one w/ travel & the local under supervisor's discretion in the FY.

**Comment by jackiekazil** [comment]
Next step -- aaron should give a thumbs up or thumbs down.

**Comment by jackiekazil** [comment]
@StephanieRivera, please update and close.

**Comment by jackiekazil** [comment]
It the digression of the employee's manager.
