### ISSUE TITLE
What is 18F FY15 Travel budget?  

### ISSUE THREAD

**Issue by StephanieRivera** [18F/training#5]
Due Date 2/13

**Comment by jackiekazil** [comment]
What is our 18F FY15 travel budget? Dollar amount.
What is our 18F training/events budget dollar amount.

**Comment by jackiekazil** [comment]
What is the difference between travel budget vs training budget? Do we have dedicated travel budget for training or is there a central travel budget or does travel associated with training come out of the main budget?

**Comment by StephanieRivera** [comment]
Budget and training are two separate budget line items and thus, need to be approved separately.

**Comment by StephanieRivera** [comment]
There is no dedicated travel budget for training.

**Comment by PiaScott** [comment]
Per discussion, FY 15 budget includes two separate line items:  $322,917 remaining for training and   $197,000 remaining for travel.  Employees require approvals for both training and travel.

**Comment by PiaScott** [comment]
Budget allotments assign each employee for training and travel.  For example, each employee will be allotted $4,000 for training and travel and $1,000 for travel.

**Comment by StephanieRivera** [comment]
Training Cap FY15 = $322,917  (approx 1.5% of PC&B (salary plus benefits for est 179 FTE) 
Employee estimate  $1,804/person
To date 18F has used $0
Limits are set by FPA (Financial Planning Application.  Changes would require a SAPi adjustment

Travel Cap FY15 = $215,000  (approx 0.8% PC&B) 
Employee estimate $1,200/person
To date  have $179K left (w/o offsite calculated)
Limit set by 18F office
