### ISSUE TITLE
Identify official Terms and Definition from GSA Policy Guidance

### ISSUE THREAD

**Issue by PiaScott** [18F/training#6]
What is the official definitions of training and conference?  What is the policy/regulation citation?

**Comment by StephanieRivera** [comment]
Official terms and definitions can be found in the appendix to GSA Workforce Learning and Development Policy

The whole policy is worth a read. 

http://gsa.gov/portal/mediaId/194047/fileName/HRM_P_94101A_GSA_Workforce_Learning_and_Development_Policy_(Final_Signed_on_6-26-2014).action

**Comment by jackiekazil** [comment]
:+1:
